# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BGL <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1) {
    .Call(`_BayesQBVSML_BGL`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1)
}

BGL_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1) {
    .Call(`_BayesQBVSML_BGL_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1)
}

BGLSS <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0) {
    .Call(`_BayesQBVSML_BGLSS`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0)
}

BGLSS_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0) {
    .Call(`_BayesQBVSML_BGLSS_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0)
}

BL <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1) {
    .Call(`_BayesQBVSML_BL`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1)
}

BL_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1) {
    .Call(`_BayesQBVSML_BL_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1)
}

BLSS <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0) {
    .Call(`_BayesQBVSML_BLSS`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0)
}

BLSS_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0) {
    .Call(`_BayesQBVSML_BLSS_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatAta, hatInvTauSq1, hatInvTauSq2, hatPiEta, hatPiBeta, invSigAlpha0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, hatPhiSq, aStar, bStar, alpha, gamma, alpha1, gamma1, mu0, nu0)
}

RBGL <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress) {
    .Call(`_BayesQBVSML_RBGL`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress)
}

RBGL_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress) {
    .Call(`_BayesQBVSML_RBGL_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress)
}

RBGLSS <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress) {
    .Call(`_BayesQBVSML_RBGLSS`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress)
}

RBGLSS_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress) {
    .Call(`_BayesQBVSML_RBGLSS_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress)
}

RBL <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress) {
    .Call(`_BayesQBVSML_RBL`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress)
}

RBL_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress) {
    .Call(`_BayesQBVSML_RBL_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, progress)
}

RBLSS <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress) {
    .Call(`_BayesQBVSML_RBLSS`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress)
}

RBLSS_1 <- function(y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress) {
    .Call(`_BayesQBVSML_RBLSS_1`, y, e, C, g, w, z, maxSteps, n, k, hatBeta, hatEta, hatAlpha, hatTau, hatV, hatSg1, hatSg2, hatAta, invSigAlpha0, hatPi1, hatPi2, hatEtaSq1, hatEtaSq2, xi1, xi2, r1, r2, hatPhiSq, a, b, alpha1, gamma1, sh1, sh0, progress)
}

